# name: Check Javascript style

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

#   workflow_dispatch:

# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Install Node modules
#         run: |
#           cd web
#           yarn install

#       - name: Run the linter
#         run: |
#           cd web
#           yarn run linter
