# name: Check container build

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

#   workflow_dispatch:

# concurrency:
#   group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Build the container
#         run: docker build .
